export const STUDENT_SESSION_COOKIE_NAME = "kr_student_session";
export const STUDENT_SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;

export const BCRYPT_SALT_ROUNDS = 10;

export const CLASS_CODE_LENGTH = 6;
export const CLASS_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const CLASS_CODE_MAX_GENERATION_ATTEMPTS = 20;
